version: '3.9'


services:
  cloudflaretunnel:
    env_file: tunnel.env
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:2023.2.1
    restart: unless-stopped
    command: tunnel --no-autoupdate run
  foundry:
    container_name: foundry
    image: node:19-bullseye
    user: node
    restart: "unless-stopped"
    ports:
      - "30000:30000"
    volumes:
      - ./FoundryVTT:/FoundryVTT
      - ./data:/data
    command: node FoundryVTT/resources/app/main.js --dataPath=/data
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SETTINGS_ENCRYPTION_KEY=
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD= #optional
    volumes:
      - /duplicaticonfig:/config
      - /backups:/backups
      - /data:/source
    ports:
      - 8200:30001
    restart: unless-stopped

