version: '3.9'


services:
  cloudflaretunnel:
    env_file: tunnel.env
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:2023.2.1
    restart: unless-stopped
    command: tunnel --no-autoupdate run
  foundry:
    container_name: foundry
    image: node:19-bullseye
    user: node
    restart: "unless-stopped"
    ports:
      - "30000:30000"
    volumes:
      - ./FoundryVTT:/FoundryVTT
      - ./data:/data
    command: node FoundryVTT/resources/app/main.js --dataPath=/data


